---
stages:
  - lint
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

lint:dockerfile:
  stage: lint
  needs: []
  image:
    name: hadolint/hadolint
    entrypoint: [""]
  script:
    - hadolint $CI_PROJECT_DIR/Dockerfile

build:dockerfile:
  stage: build
  needs: ["lint:dockerfile"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

lint:vscode:
  stage: lint
  needs: []
  image:
    name: hadolint/hadolint
    entrypoint: [""]
  script:
    - hadolint $CI_PROJECT_DIR/Dockerfile

build:vscode:
  stage: build
  needs: ["lint:vscode"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/vscode:$CI_COMMIT_TAG
