---
name: cicd

on: push

jobs:
  lint-docker:
    name: hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: hadolint
        uses: brpaz/hadolint-action@master
  build:
    name: docker-build
    runs-on: ubuntu-20.04
    needs: lint-docker
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update submodules
        run: git submodule update --init --recursive
      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} \
          | docker login https://docker.pkg.github.com -U louiscpalma --password-stdin
      - name: build utilities
        run: |
          docker build -t docker.pkg.github.com/louiscpalma/dotfiles/utilities:latest .
          && docker push docker.pkg.github.com/louiscpalma/dotfiles/utilties:latest
      - name: build vscode
        run: |
          docker build -f vscode.Dockerfile -t docker.pkg.github.com/louiscpalma/dotfiles/vscode:latest .
          && docker push docker.pkg.github.com/louiscpalma/dotfiles/vscode:latest
